name: todoey
description: Portfolio project - Simple Todo app - Users are able to create tasks and manage them, put deadlines on tasks, and mark tasks as done.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  fonts:
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf

    - family: Montserrat-Black
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
  assets:
    - assets/images/Icons/MonochromeGoogle.png
    - assets/images/bears/bearWithHat.png
    - assets/images/bears/bearWithBlackHat.png

