// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB19wQKF7lAjdHmr9Qk2WDXswMLtsaASzc',
    appId: '1:679392662911:web:fd0c30c3bdab6a1a6d364a',
    messagingSenderId: '679392662911',
    projectId: 'todoey-1bc7b',
    authDomain: 'todoey-1bc7b.firebaseapp.com',
    storageBucket: 'todoey-1bc7b.appspot.com',
    measurementId: 'G-FGKWW6JC1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMaOtYy-lIkCOPkQyaUXqjvamIKBszzh4',
    appId: '1:679392662911:android:312178b67c5d45a66d364a',
    messagingSenderId: '679392662911',
    projectId: 'todoey-1bc7b',
    storageBucket: 'todoey-1bc7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsbbz_1TntCRYHkuKM8Ci15mm7jZ9i9zM',
    appId: '1:679392662911:ios:415362e534e8ee5c6d364a',
    messagingSenderId: '679392662911',
    projectId: 'todoey-1bc7b',
    storageBucket: 'todoey-1bc7b.appspot.com',
    iosClientId: '679392662911-58tehja9hpv8rondbl1naa38li2ntbie.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsbbz_1TntCRYHkuKM8Ci15mm7jZ9i9zM',
    appId: '1:679392662911:ios:415362e534e8ee5c6d364a',
    messagingSenderId: '679392662911',
    projectId: 'todoey-1bc7b',
    storageBucket: 'todoey-1bc7b.appspot.com',
    iosClientId: '679392662911-58tehja9hpv8rondbl1naa38li2ntbie.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoey',
  );
}
